site_name: Pocket-kt
site_url: https://otisgoodman.github.io/pocket-kt/
repo_name: Pocket-kt
repo_url: https://github.com/otisgoodman/pocket-kt/
site_description: "A multi-platform idiomatic Pocketbase SDK for Koltin"
site_author: Otis Goodman
remote_branch: master
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  icon:
    logo: simple/kotlin
  palette:
    scheme: slate
    primary: deep orange
    accent: light blue
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true